Repository acm-ucr/rsd-website, pull requests merged in 2025-05, with the labels that each got.

#77 Adding mapping to upcoming events and adding wave with oar asset
  src/app/events/page.tsx
  src/components/events/UpcomingCard.tsx
Labels: Ready For Review, Changes Requested

#82 Fee Information + Assets
  src/app/join/page.tsx
  src/components/join/Registration.tsx
  src/data/FeeLabels.ts
Labels: Ready For Review

#80 Completed Practice Info Section using InfoBox.tsx, Header.tsx, PracticeShuttle.tsx, and button.tsx
  src/app/page.tsx
  src/components/home/PracticeWrapper.tsx
Labels: Ready For Review

#88 Completed Important Events using Header.tsx and InfoBox.tsx
  src/app/about/page.tsx
  src/components/about/ImportantEvents.tsx
Labels: Ready For Review

#81 Added the data for all the Board Cards, edited Board Cards to take in…
  src/app/board/page.tsx
  src/components/board/BoardCard.tsx
  src/components/board/BoardMapping.tsx
  src/data/BoardCards.ts
Labels: Ready For Review

#87 Mindisaias/history
  src/app/about/page.tsx
  src/components/about/History.tsx
Labels: Changes Requested

#91 gave proper upcoming card response to screen size
  src/app/events/page.tsx
  src/components/events/UpcomingCard.tsx
Labels: Changes Requested

#93 Adjusting Carousel
  src/components/home/GalleryPreview.tsx
Labels: Ready For Review

#99 Mindisaias/footer
  src/components/Footer.tsx
  src/data/FooterLinks.ts
Labels: Ready For Review

#69 Gallery Card
  src/app/gallery/page.tsx
  src/components/gallery/GalleryCard.tsx
Labels: Ready For Review

#102 Past Events
  src/app/events/page.tsx
Labels: Ready For Review

#108 Adding mobile navbar
  src/components/Navbar.tsx
  src/data/NavbarData.ts
Labels: Ready For Review

#109 Other Events
  src/app/gallery/page.tsx
  src/components/gallery/GalleryCard.tsx
  src/components/gallery/OtherEvents.tsx
Labels: Ready For Review

#103 Store Page Glow Up
  src/app/store/page.tsx
  src/components/store/ProductCard.tsx
  src/components/store/StickersBox.tsx
Labels: Changes Requested

#92 Added the Awards and Video in formatt
  src/app/page.tsx
  src/components/home/AwardCard.tsx
  src/components/home/AwardsMapped.tsx
  src/data/AwardsInfo.ts
Labels: Changes Requested

#117 finished the QuarterlyRaces file with a subtitle both images and the …
  src/app/gallery/page.tsx
  src/components/gallery/GalleryCard.tsx
  src/components/gallery/OtherEvents.tsx
  src/components/gallery/QuarterlyRaces.tsx
Labels: Ready For Review, Changes Requested

#121 Added Mobile Responsiveness to 404 Page
  src/app/not-found.tsx
Labels: Ready For Review

#114 Adding mobile responsivness to home page
  src/app/page.tsx
  src/components/InfoBox.tsx
  src/components/Navbar.tsx
  src/components/home/GalleryPreview.tsx
  src/components/home/PracticeShuttle.tsx
  src/components/home/PracticeWrapper.tsx
Labels: Changes Requested

#134 Ale00111/gallery mobile
  src/components/gallery/OtherEvents.tsx
  src/components/gallery/QuarterlyRaces.tsx
Labels: Ready For Review

#129 added mobile responsiveness to the sticker box component
  src/app/store/page.tsx
  src/components/store/StickersBox.tsx
Labels: Ready For Review, Changes Requested

#122 Featured products mobile responsiveness
  src/app/store/page.tsx
  src/components/store/ProductCard.tsx
Labels: Ready For Review

#135 Made Landing component mobile responsive
  src/components/home/Landing.tsx
Labels: Ready For Review
