Repository acm-ucr/rsd-website, pull requests merged in 2025-04, with the labels that each got.

#24 Gallery Preview
  components.json
  package-lock.json
  package.json
  src/app/globals.css
  src/app/page.tsx
  src/components/home/GalleryPreview.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/carousel.tsx
  src/data/GalleryImages.ts
  src/lib/utils.ts
Labels: bug, help wanted

#41 Completed Board Card Component using lucide icons and react-icons with the new changes made
  package-lock.json
  package.json
  src/components/board/BoardCard.tsx
Labels: Changes Requested

#43 Adding stickersbox
  src/app/store/page.tsx
  src/components/home/GalleryPreview.tsx
  src/components/store/StickersBox.tsx
Labels: Ready For Review

#47 Merch Card Component - changes
  src/app/store/page.tsx
  src/components/store/ProductCard.tsx
Labels: Ready For Review

#51 Completed Practice Info Times + Shuttling with new changes
  src/components/home/PracticeShuttle.tsx
Labels: Changes Requested

#54 PastEvent Component
  src/components/events/PastCard.tsx
Labels: Ready For Review

#44 Riceko/award component
  src/components/home/AwardCard.tsx
  src/components/home/GalleryPreview.tsx
Labels: Changes Requested

#55 404 Page
  src/app/not-found.tsx
Labels: Ready For Review
